#!/usr/bin/env bash

echo "watching dir $1"
echo "publishing on topic $TOPIC"
echo "to server $MOSQUITTO_URL"
inotifywait -m -r $1 | tee >(cat 1>&2) | mosquitto_pub -l -t $TOPIC -q 2 -h $MOSQUITTO_URL
